### PR TITLE
Specify Python runtime on Heroku

### PR DESCRIPTION
**Pull request by blender**
Title says it all, #13 

[Flattr this PR](https://flattr.com/submit/auto?user_id=tmpz&url=https://github.com/twilio/mobile-quickstart/pull/14&title=Twilio&language=Python&tags=github&category=software)

### CODE REVIEW

**Comment by bchen-twilio** [comment]
Hi @blender,

Thanks for reporting the issue and creating the PR!
Just want to make sure that with specifying python version as a runtime requirement, you were able to deploy the server app to Heroku and exercise the endpoints?

-bobie

**Comment by blender** [comment]
@bchen-twilio yes, you can try yourself by pressing the heroku button on my branch

**Comment by blender** [comment]
@bchen-twilio I'm confused. Since I'm not the owner of this repo you are the one that should merge. I can't.

The pr is from my branch to your master.

Since I have your attention can you please direct me to where I can get support with the iOS SDK? It is missing nullability annotation and that makes it quite worthless for Swift development. See https://github.com/TwilioDevEd/twiliochat-swift/issues/20

**Comment by bchen-twilio** [comment]
Ah I see. I'll merge the PR @blender.
Could you let us know which API specifically does not have nullability annotation? I am looking at the interface of the Voice iOS SDK but I am not able to spot one.

**Comment by blender** [comment]
@bchen-twilio Programmable Chat (TwilioChatClient.framework) 

I see a LOT of implicitly unwrapped stuff that should be optional. This makes me suspect nullability annotations are missing. For example in `TCHChannel` the Swift generated interface contains among others

```
/** Optional channel delegate.  Upon setting the delegate, you will receive the current channel synchronization status by delegate method. */
    weak open var delegate: TCHChannelDelegate!
```

In TwilioChatClient.swift among others I see

```
    /** List of channels available to the current user.
     
     This will be nil until the client is fully initialized, see the client delegate callback `chatClient:synchronizationStatusUpdated:`
     
     @return The channelsList object.
     */
    open func channelsList() -> TCHChannels!
```

clearly the return type is meant to be `TCHChannels?`

These a just a few examples but in general _every single type is implicitly unwrapped_ in the generated interface.

**Comment by rbeiter** [comment]
@blender I'm on the team taking care of the iOS Chat SDK - I've responded over on your original thread (https://github.com/TwilioDevEd/twiliochat-swift/issues/20)

**Comment by blender** [comment]
@rbeiter  Thanks. 
@bchen-twilio Please merge this PR at your earliest convenience.

**Pull request merged**
